# Generated by Django 5.0 on 2023-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='labels',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.CharField(choices=[('Indian Rupee', 'AED'), ('USD', 'USD')], max_length=20),
        ),
    ]
