# Generated by Django 5.0 on 2023-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deal_activity_deal_call_deal_notes_lead_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='call',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='call',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
