# Generated by Django 5.0 on 2023-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lead_labels_alter_lead_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.CharField(blank=True, choices=[('Indian Rupee', 'AED'), ('USD', 'USD')], max_length=20, null=True),
        ),
    ]
