# Generated by Django 5.0 on 2023-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_deal_call_alter_lead_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='Expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
