# Generated by Django 5.0 on 2023-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deal_expected_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='pipeline',
            field=models.CharField(blank=True, choices=[('pipeline', 'pipeline')], max_length=50),
        ),
    ]
