# Generated by Django 5.0 on 2023-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_deal_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
