# Generated by Django 5.0 on 2023-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_lead_email_alter_lead_labels_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='labels',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=20, null=True),
        ),
    ]
