# Generated by Django 5.0 on 2023-12-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lead_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='labels',
        ),
        migrations.AddField(
            model_name='lead',
            name='labels',
            field=models.ManyToManyField(blank=True, to='api.labels'),
        ),
    ]
