# Generated by Django 5.0 on 2023-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pipeline_deal_pipeline_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='deal',
            name='labels',
        ),
        migrations.AlterField(
            model_name='deal',
            name='pipeline',
            field=models.CharField(blank=True, choices=[('Pipeline', 'Pipeline')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='labels',
        ),
        migrations.AddField(
            model_name='deal',
            name='labels',
            field=models.ManyToManyField(blank=True, to='api.label'),
        ),
        migrations.AddField(
            model_name='lead',
            name='labels',
            field=models.ManyToManyField(blank=True, to='api.label'),
        ),
    ]
