# Generated by Django 5.0 on 2023-12-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_label_remove_deal_labels_alter_deal_pipeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='labels',
        ),
        migrations.AddField(
            model_name='lead',
            name='labels',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='deal',
            name='labels',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=20, null=True),
        ),
    ]
