# Generated by Django 5.0 on 2023-12-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_lead_labels_remove_deal_labels_lead_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
